language: php

# Versions of PHP you want your project run with.
php:
  - 5.4
  - 5.5
  - 5.6
#  - 7.0

# Commands to be run before your environment runs.
install:
  - composer self-update
  - composer update --prefer-dist

# fast_finish: If your build fails do not continue trying to build, just stop.
matrix:
  fast_finish: true

# Customize when the notification emails are sent.
notifications:
    on_success: never
    on_failure: always